server {
  listen 80;
  server_name localhost;

  # Root directory for the Angular app
  root /usr/share/nginx/html;
  index index.html index.htm;

  # Route all requests to index.html to let Angular handle routing
  location / {
    try_files $uri $uri/ /index.html;
  }
}
